class_name ClientData
extends Resource
## Represents a client contact for a DFIR case.

enum Personality {
	PANICKED_CEO,       # Non-technical, wants answers NOW, calls at midnight
	LONE_IT_ADMIN,      # Overworked, already "fixed" things, defensive
	HOSTILE_LAWYER,     # Chain-of-custody obsessed, controls narrative, limits disclosure
	COMPETENT_CISO,     # Technical, provides clean access, respects process (rare)
	IT_HERO,            # Well-meaning but tramples evidence trying to help
}

enum TrustLevel {
	HOSTILE,     # Withholds information, challenges your findings
	GUARDED,     # Shares minimum required, slow to respond
	NEUTRAL,     # Professional, shares when asked
	COOPERATIVE, # Proactively shares, quick responses
	TRUSTING,    # Full access, shares everything including embarrassing details
}

@export var client_id: String = ""
@export var name: String = ""
@export var title: String = ""  # Job title
@export var organization: String = ""
@export var industry: String = ""
@export var personality: Personality = Personality.PANICKED_CEO
@export var trust_level: TrustLevel = TrustLevel.NEUTRAL

## NPC traits that affect dialogue and behavior
@export var technical_level: float = 0.5  # 0=clueless, 1=expert
@export var stress_response: float = 0.5  # 0=calm, 1=panic
@export var honesty: float = 0.7          # 0=withholding, 1=forthcoming
@export var responsiveness: float = 0.5   # 0=slow/ignores, 1=instant replies

## Backstory for Claude NPC generation
@export_multiline var backstory: String = ""

## Dialogue data (pre-generated by Claude)
@export var dialogue_file: String = ""  # Path to dialogue JSON


func get_personality_name() -> String:
	match personality:
		Personality.PANICKED_CEO: return "Panicked CEO"
		Personality.LONE_IT_ADMIN: return "Lone IT Admin"
		Personality.HOSTILE_LAWYER: return "Hostile Lawyer"
		Personality.COMPETENT_CISO: return "Competent CISO"
		Personality.IT_HERO: return "IT Hero"
	return "Unknown"


## Trust level affects how much evidence/context the client shares
func get_evidence_access_modifier() -> float:
	match trust_level:
		TrustLevel.HOSTILE: return 0.4
		TrustLevel.GUARDED: return 0.6
		TrustLevel.NEUTRAL: return 0.8
		TrustLevel.COOPERATIVE: return 1.0
		TrustLevel.TRUSTING: return 1.0
	return 0.8
